version: '3'

services:
  postgres:
    container_name: ${POSTGRES_DB_NAME}
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    