version: '3'

services:
  postgres:
    container_name: fingreat_postgres
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - '5432:5432'
    